# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Appears in tab title bar
title: Missouri Satellite Research Team (M-SAT)

#
email: ajhq6c@mst.edu
description: > # this means to ignore newlines until "baseurl:"
  The Missouri Satellite Research Team at Missouri University of Science and Technology
  designs, builds, and tests every aspect of a flight-ready satellite, each having its own
  dedicated research mission.

# The subpath of your site, e.g. /~mrsat (this comes after url like "web.mst.edu"):
#  - For local testing (using localhost), use "/".
#  - For actual deployment (on ~mrsat), use "/~mrsat/"
baseurl: "/~iprnq9/"

# The base hostname & protocol for your site, e.g. http://example.com
# Currently, we won't need this with the way the website is built.
# In the future, if used, it would be "http://web.mst.edu" assuming that's where the site is hosted.
url: ""

# Optional Items that can be accessed on the site, e.g. "site.github_username"
# In fact, you can create whatever variables you wish to use throughout!
# twitter_username:
# github_username:

# These defaults are what variables will take place if the Front Matter doesn't overwrite them.
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      cover_image: 'images/space.jpg' # The cover image at the top of paragraphs used throughtout

# Build settings
markdown: kramdown
excerpt_separator: ""

# Ruby add-ons
# gems:

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
# include:

# What files or directories to exclude from generated site.
exclude:
  - Gemfile
  - Gemfile.lock

page_gen:
  - data: 'msat-projects'
    template: 'msat-project'
    name: 'url'
    dir: 'projects'

  - data: 'subsystems'
    template: 'subsystem'
    name: 'url'
    dir: 'subsystems'